const fs = require('fs');
const path = require('path');

// Load .env content
const envPath = path.join(__dirname, '.env');
const envContent = fs.readFileSync(envPath, 'utf8');

// Parse .env lines
const envVars = {};
envContent.split('\n').forEach(line => {
  const trimmedLine = line.trim();
  if (trimmedLine && !trimmedLine.startsWith('#')) {
    const [key, ...valueParts] = trimmedLine.split('=');
    if (key && valueParts.length > 0) {
      let value = valueParts.join('=').trim();
      value = value.replace(/^['"]|['"]$/g, ''); // Remove quotes
      envVars[key] = value;
    }
  }
});

// Generate browser-safe config content
const configContent = `// 🔧 AUTO-GENERATED FROM .env FILE 🔧
// ⚠️ DO NOT EDIT THIS FILE DIRECTLY!
// ⚠️ EDIT .env INSTEAD AND RUN: node build-config.js

window.SUPABASE_CONFIG = {
  SUPABASE_URL: "${envVars.SUPABASE_URL || ''}",
  SUPABASE_ANON_KEY: "${envVars.SUPABASE_ANON_KEY || ''}"
};
`;

// Ensure public/ folder exists
const publicDir = path.join(__dirname, 'public');
if (!fs.existsSync(publicDir)) {
  fs.mkdirSync(publicDir);
}

// Write to public/config.js
const configPath = path.join(publicDir, 'config.js');
fs.writeFileSync(configPath, configContent);

console.log('✅ config.js generated successfully in /public');
console.log('🔧 SUPABASE_URL:', envVars.SUPABASE_URL ? '✓ Loaded' : '✗ Missing');
console.log('🔧 SUPABASE_ANON_KEY:', envVars.SUPABASE_ANON_KEY ? '✓ Loaded' : '✗ Missing');
