const fs = require('fs');
const path = require('path');

// Read .env file
const envPath = path.join(__dirname, '.env');
const envContent = fs.readFileSync(envPath, 'utf8');

// Parse .env content
const envVars = {};
envContent.split('\n').forEach(line => {
    const trimmedLine = line.trim();
    if (trimmedLine && !trimmedLine.startsWith('#')) {
        const [key, ...valueParts] = trimmedLine.split('=');
        if (key && valueParts.length > 0) {
            let value = valueParts.join('=');
            // Remove quotes if present
            value = value.replace(/^['"]|['"]$/g, '');
            envVars[key] = value;
        }
    }
});

// Generate config.js file from .env variables
const configContent = `// 🔧 AUTO-GENERATED FROM .env FILE 🔧
// ⚠️  DO NOT EDIT THIS FILE DIRECTLY!
// ⚠️  EDIT .env INSTEAD AND RUN: node build-config.js
// 📝 Source: .env → build-config.js → config.js

export const config = {
    SUPABASE_URL: '${envVars.SUPABASE_URL || ''}',
    SUPABASE_ANON_KEY: '${envVars.SUPABASE_ANON_KEY || ''}'
};

export default config;
`;

// Write config.js
const configPath = path.join(__dirname, 'config.js');
fs.writeFileSync(configPath, configContent);

console.log('✅ config.js generated successfully from .env file!');
console.log('📄 Source: .env → Generated: config.js');
console.log('🔧 SUPABASE_URL:', envVars.SUPABASE_URL ? '✓ Loaded from .env' : '✗ Missing in .env');
console.log('🔧 SUPABASE_ANON_KEY:', envVars.SUPABASE_ANON_KEY ? '✓ Loaded from .env' : '✗ Missing in .env');
